"""Gate install/uninstall — register hooks with coding assistants."""

from __future__ import annotations

import json
import os
import stat
from pathlib import Path

_EDICTUM_HOOK_MARKER = "edictum gate check"


def install_claude_code(home: Path | None = None) -> str:
    """Register the edictum gate hook with Claude Code.

    Adds a PreToolUse hook entry to ~/.claude/settings.json.
    Merges with existing hooks — does NOT overwrite other hooks.
    """
    home = home or Path.home()
    settings_path = home / ".claude" / "settings.json"

    # Read existing settings
    settings: dict = {}
    if settings_path.exists():
        try:
            settings = json.loads(settings_path.read_text())
        except (json.JSONDecodeError, OSError):
            settings = {}

    if not isinstance(settings, dict):
        settings = {}

    # Build the hook entry
    hook_entry = {
        "type": "command",
        "command": "edictum gate check --format claude-code",
    }
    matcher_entry = {
        "matcher": "",
        "hooks": [hook_entry],
    }

    # Merge into existing hooks
    hooks = settings.setdefault("hooks", {})
    pre_tool_use = hooks.setdefault("PreToolUse", [])

    # Check if already installed
    for entry in pre_tool_use:
        for h in entry.get("hooks", []):
            if isinstance(h, dict) and _EDICTUM_HOOK_MARKER in h.get("command", ""):
                return "Edictum gate hook already installed in Claude Code settings"

    pre_tool_use.append(matcher_entry)

    # Write atomically
    settings_path.parent.mkdir(parents=True, exist_ok=True)
    tmp = settings_path.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(settings, indent=2) + "\n")
    os.replace(str(tmp), str(settings_path))

    return f"Installed edictum gate hook in {settings_path}"


def uninstall_claude_code(home: Path | None = None) -> str:
    """Remove the edictum gate hook from Claude Code settings."""
    home = home or Path.home()
    settings_path = home / ".claude" / "settings.json"

    if not settings_path.exists():
        return "No Claude Code settings found"

    try:
        settings = json.loads(settings_path.read_text())
    except (json.JSONDecodeError, OSError):
        return "Could not read Claude Code settings"

    hooks = settings.get("hooks", {})
    pre_tool_use = hooks.get("PreToolUse", [])

    # Filter out edictum entries
    filtered = []
    removed = False
    for entry in pre_tool_use:
        entry_hooks = entry.get("hooks", [])
        clean_hooks = [
            h for h in entry_hooks if not (isinstance(h, dict) and _EDICTUM_HOOK_MARKER in h.get("command", ""))
        ]
        if len(clean_hooks) < len(entry_hooks):
            removed = True
        if clean_hooks:
            entry["hooks"] = clean_hooks
            filtered.append(entry)

    if not removed:
        return "Edictum gate hook not found in Claude Code settings"

    hooks["PreToolUse"] = filtered
    settings["hooks"] = hooks

    tmp = settings_path.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(settings, indent=2) + "\n")
    os.replace(str(tmp), str(settings_path))

    return f"Removed edictum gate hook from {settings_path}"


def install_cline(home: Path | None = None) -> str:
    """Register the edictum gate hook with Cline."""
    home = home or Path.home()
    hooks_dir = home / "Documents" / "Cline" / "Rules" / "Hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)

    script_path = hooks_dir / "edictum-gate.sh"
    script_content = "#!/bin/bash\nedictum gate check --format cline\n"
    script_path.write_text(script_content)
    script_path.chmod(script_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    return f"Installed edictum gate hook at {script_path}"


def uninstall_cline(home: Path | None = None) -> str:
    """Remove the edictum gate hook from Cline."""
    home = home or Path.home()
    script_path = home / "Documents" / "Cline" / "Rules" / "Hooks" / "edictum-gate.sh"

    if not script_path.exists():
        return "Edictum gate hook not found for Cline"

    script_path.unlink()
    return f"Removed edictum gate hook from {script_path}"


_OPENCODE_PLUGIN_CONTENT = """\
// Edictum Gate plugin for OpenCode
// Generated by: edictum gate install opencode
import { execSync } from "child_process";

export default function(ctx) {
  return {
    "tool.execute.before": async (input, output) => {
      const payload = JSON.stringify({
        tool: input.tool,
        input: input.input,
        sessionId: ctx.sessionId || "",
        workingDirectory: ctx.cwd || process.cwd(),
      });
      try {
        const result = execSync(
          `echo '${payload.replace(/'/g, "\\'")}' | edictum gate check --format opencode`,
          { encoding: "utf-8", timeout: 5000 }
        );
        const parsed = JSON.parse(result.trim());
        if (parsed.allow === false) {
          throw new Error(parsed.reason || "Denied by edictum gate");
        }
      } catch (e) {
        if (e.message && e.message.startsWith("Denied")) throw e;
        // Fail-closed: unknown error blocks the tool call
        throw new Error("Edictum gate check failed: " + e.message);
      }
    }
  };
}
"""


def install_opencode(home: Path | None = None) -> str:
    """Register the edictum gate hook with OpenCode."""
    home = home or Path.home()
    plugins_dir = home / ".opencode" / "plugins"
    plugins_dir.mkdir(parents=True, exist_ok=True)

    plugin_path = plugins_dir / "edictum-gate.ts"
    plugin_path.write_text(_OPENCODE_PLUGIN_CONTENT)

    return f"Installed edictum gate plugin at {plugin_path}"


def uninstall_opencode(home: Path | None = None) -> str:
    """Remove the edictum gate hook from OpenCode."""
    home = home or Path.home()
    plugin_path = home / ".opencode" / "plugins" / "edictum-gate.ts"

    if not plugin_path.exists():
        return "Edictum gate plugin not found for OpenCode"

    plugin_path.unlink()
    return f"Removed edictum gate plugin from {plugin_path}"


INSTALLER_REGISTRY: dict[str, tuple] = {
    "claude-code": (install_claude_code, uninstall_claude_code),
    "cline": (install_cline, uninstall_cline),
    "opencode": (install_opencode, uninstall_opencode),
}
